### ISSUE TITLE
Secreto encontrado en código (SECRET_KEY)

### ISSUE THREAD

**Issue by cybercamphackathon** [KM-11/EIMI#1]
Se ha encontrado un secreto en el código que debería usarse desde un fichero de configuración, o en el caso de ser de test o desarrollo local, debería estar indicado en `README` o documentación/wiki:
```
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$%aao3zj%_ff39lixylx3nj!pxp!_4@^6r7!jtqee6lry8!=!z'
```
Será necesaria también la rotación de dicho secreto, en el caso de estar en uso.

https://github.com/KM-11/EIMI/blob/master/EIMI/settings.py#L22

**Comment by josE4roldan** [comment]
Hola.

Muchas gracias por revisar nuestro código.
La secret key la vamos a utilizar durante el proceso de desarrollo. En etapa de producción generaremos una nueva. La idea de mantenerla por el momento es agilizar el desarrollo.

Aquí tenéis un ejemplo para generar una nueva clave. Aunque hay otras alternativas
[https://programadorwebvalencia.com/como-generar-un-secret-key-en-django/](url)

**Comment by cybercamphackathon** [comment]
Perfecto! No os olvidéis de mencionarlo en la documentación o wiki, de todas maneras es mejor práctica el cargar los secretos desde archivos externos, y excluir los mismos en un `.gitignore`.
